AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/java17-examples-1.0-SNAPSHOT.jar
      Handler: example.HandlerIntegerJava17
      Runtime: java17
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /documents
            Method: get
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                 - dynamodb:GetItem
                 - dynamodb:PutItem
                 - dynamodb:Scan
                 - dynamodb:Query
                 - dynamodb:UpdateItem
                 - dynamodb:DeleteItem
              Resource: "arn:aws:dynamodb:your-region:your-account-id:table/YourTableName"
      Tracing: Active